[workspace]
members = [
    "package",
]

[package]
name = "scie-pants"
version = "0.1.0"
edition = "2021"
authors = [
    "John Sirois <john.sirois@gmail.com>",
]
publish = false

[profile.release]
opt-level = "s"
strip = "symbols"
lto = "fat"
codegen-units = 1

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3"

[dependencies]
anyhow = "1.0"
dirs = "4.0"
env_logger = { version = "0.10", default-features = false }
log = "0.4"
logging_timer = "1.1"
nix = "0.26"
pyver = "1.0"
serde = { workspace = true }
tempfile = { workspace = true }
toml = "0.5"
