[GLOBAL]
pants_version = "2.14.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[black]
version = "black==22.10.0"
lockfile = "pants/tool-locks/black.lock"

[isort]
version = "isort==5.10.1"
lockfile = "pants/tool-locks/isort.lock"

[mypy]
version = "mypy==0.991"
config = "tools/pyproject.toml"
lockfile = "pants/tool-locks/mypy.lock"

[pytest]
version = "pytest==7.2.0"
lockfile = "pants/tool-locks/pytest.lock"

[python]
tailor_pex_binary_targets = true
interpreter_constraints = [">=3.8,<3.10"]
resolves = { default = "tools/lock.json" }

# We generate these via cargo run -p package -- --update-lock.
resolves_generate_lockfiles = false

[source]
root_patterns = [
    "/tools",
    "/tools/src",
    "/tools/tests",
    "/tools/test_support",
]
